### ISSUE TITLE
Background issue for illegal token

### ISSUE THREAD

**Issue by golee** [bertolinimarco/vscode-theme-newton#1]
Since VSCode doesn't support background styling for token, illegal things are shown hidden;

Checkout
```json
	{
			"name": "Invalid",
			"scope": "invalid.illegal",
			"settings": {
				"background": "#f2777a",    // IGNORED
				"foreground": "#2d2d2d"
			}
		},
```

[VSCode #3429](https://github.com/Microsoft/vscode/issues/3429)

![newtonthemeerror](https://user-images.githubusercontent.com/1129665/47401658-2d8e8980-d77d-11e8-997a-3807e397725a.PNG)

And I used the workaround for now.
In settings.json in vscode
```json
"editor.tokenColorCustomizations": {		
	"textMateRules": [			
            {
                "name": "Invalid",
                "scope": "invalid.illegal",
                "settings": {
                    "foreground": "#ffffff"  // color you want
                }
            },
	],
},
````

BTW love this theme. :0

**Comment by bertolinimarco** [comment]
Thank you for the issue, soon i'll push an update to fix these and other bugs!
